<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(SharedTargetFrameworks)</TargetFrameworks>
    <RootNamespace>OrmDataAccess.Shared</RootNamespace>
    <AssemblyName>shared</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup><Compile Include="src\**\*.cs" /></ItemGroup>
</Project>
